# Generated by Django 5.0.6 on 2024-12-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActvIngDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_treatment', models.CharField(default='-', max_length=250)),
                ('alt_treatment_one', models.CharField(default='-', max_length=250)),
                ('alt_treatment_two', models.CharField(default='-', max_length=250)),
                ('disease', models.CharField(default='-', max_length=250)),
            ],
            options={
                'verbose_name': 'Treament Active Ing.',
                'verbose_name_plural': 'Treaments Active Ing.',
            },
        ),
        migrations.CreateModel(
            name='DiseaseSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(default='-', max_length=250)),
                ('symptom', models.CharField(default='-', max_length=250)),
                ('disease_class', models.CharField(default='-', max_length=550)),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
            },
        ),
    ]
