# Generated by Django 5.0.6 on 2024-12-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_advisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActvIngredientsMedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actv_ing', models.CharField(default='-', max_length=250)),
                ('drug_name', models.CharField(default='-', max_length=250)),
                ('generic_name', models.CharField(default='-', max_length=250)),
                ('drug_class', models.CharField(default='-', max_length=250)),
            ],
            options={
                'verbose_name': 'Active Ingredient Med',
                'verbose_name_plural': 'Active Ingredients Med',
            },
        ),
    ]
