# Generated by Django 5.0.6 on 2024-12-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicinePriceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(default='-', max_length=250)),
                ('drug_price', models.CharField(default='-', max_length=250)),
                ('drug_repeat', models.CharField(default='-', max_length=250)),
            ],
            options={
                'verbose_name': 'Medicine Price',
                'verbose_name_plural': 'Medicines Prices',
            },
        ),
    ]
