# Generated by Django 5.0.6 on 2024-12-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_price_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinepriceinfo',
            name='search_q',
            field=models.CharField(default='-', max_length=250),
        ),
    ]
