# Generated by Django 5.0.6 on 2024-11-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(default='-', max_length=250)),
                ('generic_name', models.CharField(default='-', max_length=250)),
                ('drug_class', models.CharField(default='-', max_length=250)),
                ('similars', models.CharField(default='-', max_length=250)),
                ('alternatives', models.CharField(default='-', max_length=250)),
            ],
        ),
    ]
