# Generated by Django 5.0.6 on 2024-11-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicineinfo',
            options={'verbose_name': 'Medicine', 'verbose_name_plural': 'Medicines'},
        ),
    ]
